### PR TITLE
Implement Info Tab

### PR DESCRIPTION
**Pull request by maikkundev**
In order to change what is shown in the Info Tab, the `./web/info.md` needs to be modified.

### CODE REVIEW

**Comment by maikkundev** [comment]
Should the Info Tab be the Home tab as well or should they be separated?

**Comment by actuallylost** [comment]
If the original pdf mentions Info & Home tab yes, just let me know if it does so I can rename the issues and PR. @maikkundev

**Comment by maikkundev** [comment]
IIRC there's no mention of a Home tab on the PDF but we could include one or rename Info to Home to make the app feel more like an actual thing. @actuallylost

**Comment by actuallylost** [comment]
Then it's out of the scope of this application and this pull request.

**Review by actuallylost — APPROVED** [review]
Looks good to me!

**Pull request merged**
